name: run-data-science-tools-unit-tests
on:
  push:
    branches-ignore:
      - main
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: conda environment
        run: |
          $CONDA/bin/conda env update --file environment.yml --name base
      - name: run-data-science-tools-unit-tests
        run: |
          $CONDA/bin/pytest
